export const gameCellTypes = {
  GENERATE_RANDOM: 'GENERATE_RANDOM',
  SET_CANVAS_COLOR: 'SET_CANVAS_COLOR',
  TOGGLE_RUN: 'TOGGLE_RUN',
  FILL_CURRENT_FIELD: 'FILL_CURRENT_FIELD',
  SET_TRIGGER: 'SET_TRIGGER',
};
