export const interfaceTypes = {
  MOVE_ITEM_OF_INTERFACE: 'MOVE_ITEM_OF_INTERFACE',
  TOGGLE_THEME_BAR: 'TOGGLE_THEME_BAR',
  TOGGLE_CONFIG_BAR: 'TOGGLE_CONFIG_BAR',
  SET_BORN: 'SET_BORN',
  SET_ALIVE: 'SET_ALIVE',
  SET_USER_VIEW: 'SET_USER_VIEW',
  TOGGLE_PRESET_BAR: 'TOGGLE_PRESET_BAR',
};
